### ISSUE TITLE
e.windowControlsOverlay.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by Levminer** [6c65726f79/custom-titlebar#100]
Hi!

After upgrading to Electron 17 I get an error:
```
Uncaught TypeError: e.windowControlsOverlay.getBoundingClientRect is not a function
```
I tried setting windowControlsOverlay to false, I get the same error.

**Comment by 6c65726f79** [comment]
Hi, thank you for reporting this issue, I'll try to fix it today. I hope this is not a bug from Electron.

**Comment by Levminer** [comment]
Thanks for the fast fix!
