### ISSUE TITLE
If something is under the titlebar can't move window

### ISSUE THREAD

**Issue by Levminer** [6c65726f79/custom-titlebar#64]
Hi!

If something scrolls under the titlebar you can't move the window, but only there when something scolls under it:
I tried messing with z-index but no results.

![image](https://user-images.githubusercontent.com/33373714/145711376-1f5fbf1b-bc2f-4bec-88bd-2dff984fc027.png)

**Comment by 6c65726f79** [comment]
Hi, thank you for reporting this issue. Can you give me the structure of your HTML page and your CSS so I can try to reproduce it? Thanks.
And have you tried to add some custom CSS for `.custom-titlebar-container`?

**Comment by 6c65726f79** [comment]
I've looked at the source code of your authme app, and the problem come from the global.css file, you should remove the `-webkit-app-region: no-drag;` from `*,::before,::after` unless it's necessary. I hope this helps.

**Comment by Levminer** [comment]
Oh, thank you for your help! Great job with the packge btw!

**Comment by 6c65726f79** [comment]
You're welcome! And thanks, I'm glad to see it used in an app like yours.

Also, you should not use the randomly generated CSS classes to customize elements, as they will change with each update. So I added some [custom classes](https://github.com/6c65726f79/custom-titlebar#css-classes) in the latest release.
