### ISSUE TITLE
minimizable, maximizable, and closeable

### ISSUE THREAD

**Issue by fznhq** [6c65726f79/custom-titlebar#76]
How to do that? Should this feature be added to this library?

**Comment by 6c65726f79** [comment]
Yes I was planning to add this feature. I'll try to do it today.

**Comment by fznhq** [comment]
Thanks, my current solution is a bit messy, so yeah I'll update the library as soon as the feature implemented

**Comment by 6c65726f79** [comment]
Options added in [v0.8.0](https://github.com/6c65726f79/custom-titlebar/blob/main/CHANGELOG.md#v080). Thanks for your interest.
